services:
  - type: web
    name: vip-userbot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python3 -m VIP"
    envVars:
      - key: API_ID
        value: your_api_id_here
      - key: API_HASH
        value: your_api_hash_here
      - key: SESSION_STRING
        value: your_pyrogram_or_telethon_session
